#!/usr/bin/env sh
# Generates the Homebrew tap files (to stdout) from a release version + asset checksums.
# The release workflows use this to push bumps to fredoliveira/homebrew-tap automatically;
# it also works by hand:
#
#   generate.sh formula <version> <sha256-macos-arm64> <sha256-macos-x86_64> <sha256-linux-x86_64>
#   generate.sh cask    <version> <sha256-dmg>
#
# <version> is bare (0.1.3), not the tag (v0.1.3).
set -eu

mode="$1"
version="$2"
base="https://github.com/fredoliveira/17lands-rust/releases/download/v${version}"

case "$mode" in
formula)
  sha_arm="$3" sha_mac_intel="$4" sha_linux="$5"
  cat <<EOF
# Homebrew formula for seventeenlands-rust (binary "pour" — no Rust toolchain needed).
#
# GENERATED by packaging/homebrew/generate.sh in fredoliveira/17lands-rust — the release
# workflow pushes a bump here on every tagged release. Edit the generator, not this file.
#
# Users install with:
#
#     brew install fredoliveira/tap/seventeenlands-rust
class SeventeenlandsRust < Formula
  desc "Rust port of the 17Lands MTGA log client (uploads MTG Arena data to 17lands.com)"
  homepage "https://github.com/fredoliveira/17lands-rust"
  license "GPL-3.0-only"

  on_macos do
    on_arm do
      url "${base}/seventeenlands-rust-aarch64-apple-darwin.tar.gz"
      sha256 "${sha_arm}"
    end
    on_intel do
      url "${base}/seventeenlands-rust-x86_64-apple-darwin.tar.gz"
      sha256 "${sha_mac_intel}"
    end
  end

  on_linux do
    on_intel do
      url "${base}/seventeenlands-rust-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${sha_linux}"
    end
  end

  def install
    bin.install "seventeenlands"
  end

  test do
    assert_match "17lands.com", shell_output("#{bin}/seventeenlands --help")
  end
end
EOF
  ;;
cask)
  sha_dmg="$3"
  cat <<EOF
# Homebrew Cask for the 17Lands desktop app (menu-bar).
#
# GENERATED by packaging/homebrew/generate.sh in fredoliveira/17lands-rust — the release
# workflow pushes a bump here on every tagged release. Edit the generator, not this file.
#
# Users install with:
#
#     brew install --cask fredoliveira/tap/seventeenlands-desktop
#
# NOTE: the app is currently only ad-hoc signed (not Apple-notarized), so Gatekeeper
# quarantines it on first launch. Until notarization is set up, open it once via
# right-click -> Open, or clear the quarantine attribute:
#     xattr -dr com.apple.quarantine "/Applications/17Lands.app"
cask "seventeenlands-desktop" do
  version "${version}"
  sha256 "${sha_dmg}"

  url "https://github.com/fredoliveira/17lands-rust/releases/download/v#{version}/17Lands-universal.dmg"
  name "17Lands"
  desc "Menu-bar app that uploads MTG Arena data to 17lands.com"
  homepage "https://github.com/fredoliveira/17lands-rust"

  depends_on macos: ">= :big_sur"

  app "17Lands.app"

  zap trash: "~/Library/Application Support/17l"
end
EOF
  ;;
*)
  echo "usage: generate.sh formula|cask <version> <sha256...>" >&2
  exit 64
  ;;
esac
